# inventory.ini
# This file lists all the machines Ansible will manage
# For this project we use localhost (our own machine)

[local]
localhost ansible_connection=local

# ansible_connection=local means no SSH needed
# Ansible will run commands directly on this machine